### ISSUE TITLE
Existing EPS driver code review

### ISSUE THREAD

**Issue by ViciousDoormat** [davincisatellite/msp-flightsoftware#33]
Relevant for: @Dennisman219 @DavidGhergut 

- [x] There are multiple occasions where a bitshift to the left is performed with 1 on the received bytes, while this (probably) should be with 8.
- [x] get_pbu_housekeeping_data_raw sends as ID (or CC) 0x62. However, that's the ID of PBU housekeeping data ENG. The ID of PBU housekeeping data RAW is 0x60
- [x] output_bus_channel_off sends 6 bytes, but it should only send 5 bytes. I think the 0x16 should not be there.
- [x] reset_configuration sends as IVID code 0x02. However, according to the document, only 0x06 is accepted. Every other command does indeed send 0x06

**Comment by ViciousDoormat** [comment]
> reserve bytes should be checked for consistency (usually they should be 0x00), so the code should ensure that the reserved byte holds the expected value and report an error if doesn't (see example page 44, EPS Software ICD IVID)

@DavidGhergut, Where on page 44 does it say reserved bytes should be consistent and usually be 0x00?
You refer to the example, so I assume you refer to:
"Usage Example: 
Transfer the following bytes to the system. 
{ STID IVID 0x44 BID} 
Upon reception of the command, the system places the latest ABF state data in the read buffer. The data is returned during 
the next read transaction. The STAT NEW bit is set when the accompanying data represents new measurement information 
that is retrieved for the first time."
But this says nothing about the reserved data.

I also cannot find anything about it in the document.

**Comment by DavidGhergut** [comment]
@ViciousDoormat I think you are right, because at that time I was referring to this part from page 44 from the ICD regarding the reserved bytes, but in this screenshot it is about the ABF_PLACED_0 which is different from the reserve bytes, so I think as well there is no requirement on reserve bytes being 0x00!

![image](https://github.com/user-attachments/assets/4178a75d-872d-453c-8484-e10249b21922)
